package com.arg.springonline.controllers;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;



import com.arg.springonline.entities.User;
import com.arg.springonline.repositories.UserRepository;

@Controller
public class UserController {

	private Logger logger = LoggerFactory.getLogger(UserController.class);
	
	@Autowired 
	// This means to get the bean called userRepository, Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@GetMapping("/users")
	public String users(ArrayList<User> users, Model model) {
		
		List<User> retrievedUsers = (List<User>) userRepository.findAll();
		model.addAttribute("users", retrievedUsers);
		logger.info("Retrieving " + retrievedUsers.size() + " users");
		return "users";
	}

	@GetMapping("/user")
	public String greetingForm(Model model) {
		model.addAttribute("user", new User());
		return "user";
	}

	@PostMapping("/user")
	public String userSubmit(@ModelAttribute User user, Model model) {
		userRepository.save(user);
		logger.info("Storing new user: " + user);
		model.addAttribute("user", user);
		return "userResult";
	}

}