package com.example.servingwebcontent.controllers;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.example.servingwebcontent.entities.User;
import com.example.servingwebcontent.repositories.UserRepository;


@Controller
public class UserController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
private UserRepository userRepository;
	
	@GetMapping("/users")
	public String users(ArrayList<User> users,Model model) {
		model.addAttribute("users",(List<User>) userRepository.findAll());
		return "users";
	}
	
	@GetMapping("/user")
	  public String greetingForm(Model model) {
	    model.addAttribute("user", new User());
	    return "user";
	  }

	  @PostMapping("/user")
	  public String userSubmit(@ModelAttribute User user, Model model) {
		userRepository.save(user);
	    model.addAttribute("user", user);
	    return "userResult";
	  }

}